os: osx
language: node_js
node_js:
  - "4.2.3"
services:
  - mongodb
before_script:
  - brew update
  - brew install mongodb
  - brew services start mongodb
script:
  - sleep 15
  - npm test
  - npm install -g gulp
  - gulp
  - gulp webpack:test
  - npm install -g karma
  - karma start
