os: osx
language: node_js
node_js:
  - "4.2.3"
services:
  - mongodb
before_script:
  - sleep 15
  - ./mongod --dbpath=./db
# env:
#   - CXX=g++-4.8
# script:
#   -
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
#       - opencl-headers
#       - nvidia-opencl-dev
