os: osx
language: node_js
node_js:
  - "4.2.3"
services:
  - mongodb
before_script:
  - brew install mongodb
  - brew services start mongodb
script:
  - sleep 15
  # - mongo mydb_test --eval 'db.addUser("travis", "test");'
# env:
#   - CXX=g++-4.8
# script:
#   -
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
#       - opencl-headers
#       - nvidia-opencl-dev
